name: Vagrant Tutorial
description: Blogging about stuffs
meta_description: "A simple tutorial for using Vagrant"

aboutPage: true

markdown: redcarpet
highlighter: pygments

baseurl: /virtualbox-tutorial/
domain_name: 'http://sabinmarcu.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://infoeducatie.ro'
author:         'Sabin Marcu & Elena Pistol'
authorTwitter:  ''

permalink:       /:year/:title/
redcarpet:
    extensions: [with_toc_data, tables]

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
